image: jch254/docker-node-serverless:latest
pipelines:
  branches:
    master:
      - step:
          script:
            - yarn install --ignore-engines
            - export NODE_ENV=production
            - serverless deploy
